# Generated by Django 2.1.5 on 2019-01-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hamburgueria', '0002_auto_20190110_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pedido', to='Hamburgueria.Pedido'),
        ),
        migrations.AddField(
            model_name='produto_pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_produto', to='Hamburgueria.Produto'),
        ),
    ]
