# Generated by Django 2.1.5 on 2019-01-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hamburgueria', '0003_auto_20190110_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto_Pedido',
            new_name='ProdutoPedido',
        ),
    ]
