# Generated by Django 2.1.5 on 2019-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamburgueria', '0006_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('L', 'Lanches'), ('B', 'Bebidas'), ('S', 'Sobremesas')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
