# Generated by Django 2.1.5 on 2019-01-10 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hamburgueria', '0007_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produtopedido',
            options={'verbose_name': 'ProdutoPedidos', 'verbose_name_plural': 'ProdutosPedido'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedido', to='Hamburgueria.Pedido'),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='Hamburgueria.Produto'),
        ),
    ]
