# Generated by Django 2.1.5 on 2019-01-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamburgueria', '0008_auto_20190110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('P', 'Pedido Efetuado'), ('A', 'Atendito'), ('E', 'Entregando'), ('X', 'Entregue')], default='P', max_length=1),
        ),
    ]
