# Generated by Django 2.1.5 on 2019-01-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hamburgueria', '0009_auto_20190110_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarrinhoItem', to=settings.AUTH_USER_MODEL)),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrinho', to='Hamburgueria.Produto')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('P', 'Pedido Efetuado'), ('A', 'Em Andamento'), ('E', 'Entregando'), ('X', 'Entregue'), ('C', 'Carrinho')], default='P', max_length=1),
        ),
    ]
