# Generated by Django 2.1.5 on 2019-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamburgueria', '0010_auto_20190111_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
